#!/bin/sh
uci set network.lan.ipaddr='192.168.9.1'
uci set system.@system[0].hostname='DulWiFi'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit network
uci commit system
uci commit luci
/etc/init.d/dulwifi-firstboot enable
exit 0
