#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service() {
  [ -f /etc/dulwifi-firstboot.done ] && return 0
  procd_open_instance
  procd_set_param command /usr/libexec/dulwifi-firstboot
  procd_set_param respawn 3600 10 5
  procd_close_instance
}
